name: 'Autocomment-atime-results'
author: 'Anirban Chetia'
description: 'Autocomment atime-based performance regression analysis on PRs'
branding:
  icon: 'message-square'
  color: 'gray-dark'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Manage refs
      run: |
        git switch "${GITHUB_BASE_REF}"
        git switch "${GITHUB_HEAD_REF}"
        git for-each-ref --format="%(refname)" | while read ref; do
          git show-ref --quiet --verify $ref 2>/dev/null || git update-ref -d $ref
        done
      shell: bash

    - name: R Setup
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: Set up the required system dependency libgit2
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libgit2-dev
      shell: bash  

    - name: Install atime and initiate magic
      run: |
        start=`date +%s`
        R -e 'r = getOption("repos"); r["CRAN"] = "http://cran.us.r-project.org"; options(repos = r); install.packages("atime", dependencies = TRUE); atime::atime_pkg(Sys.getenv("GITHUB_WORKSPACE"))'
        end=`date +%s`
        runtime=$((end-start))
        echo "ATIME_STEP_RUNTIME=$((end-start))" >> $GITHUB_ENV
      shell: bash

    - name: Upload results
      id: artifact-upload-step
      uses: actions/upload-artifact@v4
      with:
        name: atime-results
        path: inst/atime/

    - name: Push generated plot along with relevant information on the PR thread as a GH-bot comment
      run: |
        echo "![Comparison Plot](./inst/atime/tests_all_facet.png)" >> report.md
        echo -e "\nGenerated via commit ${{ github.event.pull_request.head.sha }}" >> report.md
        echo -e "\nDownload link for the artifact containing the test results: [↓ atime-results.zip](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }})" >> report.md
        echo -e "\nTime taken to install \`atime\` and run \`atime_pkg\` on the test(s): $((ATIME_STEP_RUNTIME%3600/60)) minutes and $((ATIME_STEP_RUNTIME%60)) seconds" >> report.md
        cml comment update report.md
      shell: bash
