name: Autocomment articfact link (atime-based regression analysis plot) on PRs

on:
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - synchronize

jobs:
  comment:
    runs-on: ubuntu-latest

steps:
    - name: Checkout
      uses: actions/checkout@v2