name: Autocomment articfact link (atime-based regression analysis plot) on PRs

on:
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - synchronize

jobs:
  comment:
    runs-on: ubuntu-latest

steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Collect PR identifier
      run: |
        PR_SHA="${{ github.event.pull_request.head.sha }}"
        echo "PR_SHA=${PR_SHA}" >> $GITHUB_ENV
      shell: bash

    - name: setup
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: Install dependencies
      run: |
        Rscript -e 'install.packages(c("ggplot2", "devtools", "directlabels"))'

    - name: Comment on PR
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Test message'
          })