name: Autocomment articfact link (atime-based regression analysis plot) on PRs

on:
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - synchronize

jobs:
  comment:
    runs-on: ubuntu-latest

steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Collect PR identifier
      run: |
        PR_SHA="${{ github.event.pull_request.head.sha }}"
        echo "PR_SHA=${PR_SHA}" >> $GITHUB_ENV
      shell: bash

    - name: setup
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: Install dependencies
      run: |
        Rscript -e 'install.packages(c("ggplot2", "devtools", "directlabels"))'

    - name: Generate plot
      run: |
        Rscript -e 'library(ggplot2); ggplot(diamonds) + geom_point(aes(x = carat, y = price, color = cut)) + geom_smooth(aes(x = carat, y = price, color = cut)); ggsave(filename = 'plot.png', plot = last_plot())'

    - name: PR comment with file
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: ./plot.png

    - name: upload-artifact
      uses: actions/upload-artifact@v3
      with:
        name: plot
        path: ./plot.png  