name: Autocomment atime-based regression analysis plot on PRs

on:
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - synchronize

jobs:
  comment:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: R Setup
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: Install R dependencies
      run: |
        Rscript -e 'install.packages(c("ggplot2", "devtools", "directlabels", "remotes"))'

    - name: Setup required system dependencies (libgit2 and git2r)
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libgit2-dev
        git clone https://github.com/ropensci/git2r.git
        cd git2r && make install
        cd ..
        git clone https://github.com/Anirban166/data.table.git
        R -e 'remotes::install_github("tdhock/atime")'
